[project]
name = "agentic-lab"
version = "0.1.0"
description = ""
authors = [
    {name = "Quantiphi"}
]
package-mode = false
readme = "README.md"
requires-python = "3.10.12"
dependencies = [
    "absl-py (==2.1.0)",
    "accelerate (==1.11.0)",
    "annotated-types (==0.7.0)",
    "anyio (==4.11.0)",
    "argon2-cffi (==23.1.0)",
    "argon2-cffi-bindings (==21.2.0)",
    "arrow (==1.4.0)",
    "asttokens (==2.4.1)",
    "astunparse (==1.6.3)",
    "async-lru (==2.0.5)",
    "attrs (==23.2.0)",
    "audioread (==3.0.1)",
    "babel (==2.17.0)",
    "backoff (==2.2.1)",
    "bcrypt (==5.0.0)",
    "beautifulsoup4 (==4.12.3)",
    "bleach (==6.1.0)",
    "blis (==0.7.11)",
    "build (==1.3.0)",
    "cachetools (==5.3.3)",
    "catalogue (==2.0.10)",
    "certifi (==2024.6.2)",
    "cffi (==1.16.0)",
    "charset-normalizer (==3.3.2)",
    "chromadb (==1.3.5)",
    "click (==8.1.7)",
    "cloudpathlib (==0.16.0)",
    "cmake (==3.29.3)",
    "colorama (==0.4.6)",
    "coloredlogs (==15.0.1)",
    "comm (==0.2.2)",
    "confection (==0.1.5)",
    "contourpy (==1.2.1)",
    "cycler (==0.12.1)",
    "cymem (==2.0.8)",
    "cython (==3.0.10)",
    "dataclasses-json (==0.6.7)",
    "datasets (==4.4.1)",
    "debugpy (==1.8.1)",
    "decorator (==5.1.1)",
    "defusedxml (==0.7.1)",
    "dill (==0.4.0)",
    "distro (==1.9.0)",
    "dm-tree (==0.1.8)",
    "durationpy (==0.10)",
    "einops (==0.8.0)",
    "exceptiongroup (==1.2.1)",
    "execnet (==2.1.1)",
    "executing (==2.0.1)",
    "expecttest (==0.1.3)",
    "fastjsonschema (==2.19.1)",
    "filelock (==3.14.0)",
    "filetype (==1.2.0)",
    "flatbuffers (==25.9.23)",
    "fonttools (==4.53.0)",
    "fqdn (==1.5.1)",
    "gast (==0.5.4)",
    "gitdb (==4.0.12)",
    "gitpython (==3.1.45)",
    "google-auth (==2.29.0)",
    "google-auth-oauthlib (==0.4.6)",
    "googleapis-common-protos (==1.72.0)",
    "greenlet (==3.2.4)",
    "grpcio (==1.76.0)",
    "h11 (==0.16.0)",
    "hf-xet (==1.2.0)",
    "httpcore (==1.0.9)",
    "httptools (==0.7.1)",
    "httpx (==0.28.1)",
    "httpx-sse (==0.4.3)",
    "huggingface-hub (==0.36.0)",
    "humanfriendly (==10.0)",
    "hypothesis (==5.35.1)",
    "idna (==3.7)",
    "igraph (==0.11.5)",
    "importlib-resources (==6.5.2)",
    "iniconfig (==2.0.0)",
    "intel-openmp (==2021.4.0)",
    "ipykernel (==6.29.4)",
    "ipython (==8.21.0)",
    "ipython-genutils (==0.2.0)",
    "ipywidgets (==8.1.8)",
    "isoduration (==20.11.0)",
    "jedi (==0.19.1)",
    "jinja2 (==3.1.4)",
    "jiter (==0.12.0)",
    "joblib (==1.4.2)",
    "json5 (==0.9.25)",
    "jsonpatch (==1.33)",
    "jsonpointer (==3.0.0)",
    "jsonschema (==4.22.0)",
    "jsonschema-specifications (==2023.12.1)",
    "jupyter-events (==0.12.0)",
    "jupyter-lsp (==2.3.0)",
    "jupyter-server-mathjax (==0.2.6)",
    "jupyter-client (==8.6.2)",
    "jupyter-core (==5.7.2)",
    "jupyter-server (==2.17.0)",
    "jupyter-server-terminals (==0.5.3)",
    "jupyterlab (==4.4.10)",
    "jupyterlab-git (==0.51.2)",
    "jupyterlab-pygments (==0.3.0)",
    "jupyterlab-server (==2.28.0)",
    "jupyterlab-widgets (==3.0.16)",
    "jupytext (==1.16.2)",
    "kiwisolver (==1.4.5)",
    "kubernetes (==34.1.0)",
    "langchain (==1.0.8)",
    "langchain-classic (==1.0.0)",
    "langchain-community (==0.4.1)",
    "langchain-core (==1.0.7)",
    "langchain-nvidia-ai-endpoints (>=0.3.0)",
    "langchain-openai (==1.0.3)",
    "langchain-text-splitters (==1.0.0)",
    "langcodes (==3.4.0)",
    "langgraph (>=1.0.3,<2.0.0)",
    "langgraph-checkpoint (==3.0.1)",
    "langgraph-prebuilt (==1.0.5)",
    "langgraph-sdk (==0.2.9)",
    "langsmith (==0.4.45)",
    "language-data (==1.2.0)",
    "lazy-loader (==0.4)",
    "librosa (==0.10.1)",
    "lightning-utilities (==0.11.2)",
    "lintrunner (==0.12.5)",
    "llvmlite (==0.42.0)",
    "looseversion (==1.3.0)",
    "marisa-trie (==1.1.1)",
    "markdown (==3.6)",
    "markdown-it-py (==3.0.0)",
    "markupsafe (==2.1.5)",
    "marshmallow (==3.26.1)",
    "matplotlib (==3.9.0)",
    "matplotlib-inline (==0.1.7)",
    "mdit-py-plugins (==0.4.1)",
    "mdurl (==0.1.2)",
    "mistune (==3.0.2)",
    "mkl (==2021.1.1)",
    "mkl-devel (==2021.1.1)",
    "mkl-include (==2021.1.1)",
    "mmh3 (==5.2.0)",
    "mock (==5.1.0)",
    "mpmath (==1.3.0)",
    "msgpack (==1.0.8)",
    "multiprocess (==0.70.18)",
    "murmurhash (==1.0.10)",
    "mypy-extensions (==1.1.0)",
    "nbclient (==0.10.0)",
    "nbconvert (==7.16.4)",
    "nbdime (==4.0.2)",
    "nbformat (==5.10.4)",
    "nest-asyncio (==1.6.0)",
    "networkx (==3.3)",
    "ninja (==1.11.1.1)",
    "notebook (==7.4.7)",
    "notebook-shim (==0.2.4)",
    "numba (==0.59.1)",
    "numpy (==1.26.4)",
    "nvidia-dali-cuda120 (==1.38.0)",
    "nvidia-modelopt (==0.11.2)",
    "nvidia-nvimgcodec-cu12 (==0.2.0.7)",
    "oauthlib (==3.2.2)",
    "onnxruntime (==1.23.2)",
    "openai (==2.8.1)",
    "opentelemetry-api (==1.38.0)",
    "opentelemetry-exporter-otlp-proto-common (==1.38.0)",
    "opentelemetry-exporter-otlp-proto-grpc (==1.38.0)",
    "opentelemetry-proto (==1.38.0)",
    "opentelemetry-sdk (==1.38.0)",
    "opentelemetry-semantic-conventions (==0.59b0)",
    "opt-einsum (==3.3.0)",
    "optree (==0.11.0)",
    "orjson (==3.11.4)",
    "ormsgpack (==1.12.0)",
    "overrides (==7.7.0)",
    "packaging (==24.0)",
    "pandocfilters (==1.5.1)",
    "parso (==0.8.4)",
    "pexpect (==4.9.0)",
    "pillow (==10.3.0)",
    "platformdirs (==4.2.2)",
    "pluggy (==1.5.0)",
    "pooch (==1.8.1)",
    "posthog (==5.4.0)",
    "preshed (==3.0.9)",
    "prettytable (==3.10.0)",
    "prometheus-client (==0.20.0)",
    "prompt-toolkit (==3.0.45)",
    "protobuf (==6.33.1)",
    "psutil (==5.9.8)",
    "ptyprocess (==0.7.0)",
    "pure-eval (==0.2.2)",
    "pyarrow (==22.0.0)",
    "pyasn1 (==0.6.0)",
    "pyasn1-modules (==0.4.0)",
    "pybase64 (==1.4.2)",
    "pybind11 (==2.12.0)",
    "pybind11-global (==2.12.0)",
    "pycparser (==2.22)",
    "pydantic (==2.12.4)",
    "pydantic-settings (==2.12.0)",
    "pydantic-core (==2.41.5)",
    "pygments (==2.18.0)",
    "pyparsing (==3.1.2)",
    "pypika (==0.48.9)",
    "pyproject-hooks (==1.2.0)",
    "pytest (==8.1.1)",
    "pytest-flakefinder (==1.1.0)",
    "pytest-rerunfailures (==14.0)",
    "pytest-shard (==0.1.2)",
    "pytest-xdist (==3.6.1)",
    "python-dateutil (==2.9.0.post0)",
    "python-dotenv (==1.2.1)",
    "python-hostlist (==1.23.0)",
    "python-json-logger (==4.0.0)",
    "pyyaml (==6.0.1)",
    "pyzmq (==26.0.3)",
    "referencing (==0.35.1)",
    "regex (==2024.5.15)",
    "requests (==2.32.5)",
    "requests-oauthlib (==2.0.0)",
    "requests-toolbelt (==1.0.0)",
    "rfc3339-validator (==0.1.4)",
    "rfc3986-validator (==0.1.1)",
    "rpds-py (==0.18.1)",
    "rsa (==4.9)",
    "sacremoses (==0.1.1)",
    "safetensors (==0.6.2)",
    "scikit-learn (==1.5.0)",
    "send2trash (==1.8.3)",
    "sentence-transformers (==5.1.2)",
    "sentencepiece (==0.2.1)",
    "six (==1.16.0)",
    "smart-open (==6.4.0)",
    "smmap (==5.0.2)",
    "sniffio (==1.3.1)",
    "sortedcontainers (==2.4.0)",
    "soundfile (==0.12.1)",
    "soupsieve (==2.5)",
    "soxr (==0.3.7)",
    "spacy (==3.7.4)",
    "spacy-legacy (==3.0.12)",
    "spacy-loggers (==1.0.5)",
    "sphinx-glpi-theme (==0.6)",
    "sqlalchemy (==2.0.44)",
    "srsly (==2.4.8)",
    "stack-data (==0.6.3)",
    "tabulate (==0.9.0)",
    "tavily-python (==0.7.13)",
    "tbb (==2021.12.0)",
    "tenacity (==9.1.2)",
    "tensorboard (==2.9.0)",
    "tensorboard-data-server (==0.6.1)",
    "tensorboard-plugin-wit (==1.8.1)",
    "terminado (==0.18.1)",
    "texttable (==1.7.0)",
    "thinc (==8.2.3)",
    "threadpoolctl (==3.5.0)",
    "tiktoken (==0.12.0)",
    "tinycss2 (==1.3.0)",
    "tokenizers (==0.22.1)",
    "tomli (==2.0.1)",
    "tornado (==6.4)",
    "tqdm (==4.66.4)",
    "traitlets (==5.9.0)",
    "transformers (==4.57.1)",
    "typer (==0.9.4)",
    "types-dataclasses (==0.6.6)",
    "typing-inspect (==0.9.0)",
    "typing-inspection (==0.4.2)",
    "typing-extensions (==4.15.0)",
    "uri-template (==1.3.0)",
    "uvicorn (==0.38.0)",
    "uvloop (==0.22.1)",
    "wasabi (==1.1.3)",
    "watchfiles (==1.1.1)",
    "wcwidth (==0.2.13)",
    "weasel (==0.3.4)",
    "webcolors (==25.10.0)",
    "webencodings (==0.5.1)",
    "websocket-client (==1.9.0)",
    "websockets (==15.0.1)",
    "werkzeug (==3.0.3)",
    "widgetsnbextension (==4.0.15)",
    "xdoctest (==1.0.2)",
    "xxhash (==3.6.0)",
    "zstandard (==0.25.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
